# Generated by Django 4.2 on 2023-11-16 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('img', models.ImageField(default='default.jpg', upload_to='student_pics')),
                ('batch', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
                ('year', models.CharField(choices=[('F.E.', 'First year'), ('S.E.', 'Second year'), ('T.E.', 'Third year'), ('B.E.', 'Fourth year')], default='F.E.', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AB', 'Absent'), ('P', 'Present')], default='AB', max_length=2)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.pupil')),
            ],
        ),
    ]
