# Generated by Django 4.2 on 2023-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='uid',
        ),
        migrations.AddField(
            model_name='attendance',
            name='uid',
            field=models.ManyToManyField(to='student.pupil'),
        ),
    ]
