# Generated by Django 4.2 on 2023-11-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_attendance_uid_attendance_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='uid',
            new_name='pupils',
        ),
    ]
